### PR TITLE
Update Project.toml

### PR DESCRIPTION
**Pull request by jheinen**
bump GR version

### CODE REVIEW

**Comment by jheinen** [comment]
@heliosdrm : Could you please merge #98 ? Thanks.

**Comment by heliosdrm** [comment]
I didn't merge because it was not working properly: GRUtils was using some constants of GR that had been turned into `Ref`s, and there were also issues with volume plots and other things seemingly related with the latest changes. I'm fixing that, and as soon as I get it solved, I'll merge this too.

**Comment by jheinen** [comment]
That's strange. The test pass and the volume plot is fixed IMO. The "old" 3D transformation is still supported and should work.

**Comment by heliosdrm** [comment]
This PR is replaced by #99

**Pull request closed without merging**
